/***********************************************************
 * File generated by the HALCON-Compiler hcomp version 17.12
 * Usage: Interface to C++
 *
 * Software by: MVTec Software GmbH, www.mvtec.com
 ***********************************************************/


#ifndef HCPP_HDLCONFIGINI
#define HCPP_HDLCONFIGINI

namespace HalconCpp
{




  /***************************************************************************
   * Operators                                                               *
   ***************************************************************************/

// 	ex_copy_file.
HUserExport void ExCopyFile(const HTuple& src, const HTuple& dist);

// 	ex_mapviewoffileread
HUserExport void ExMapviewoffilereadimage(HObject* Image, const HTuple& iHandle, const HTuple& startindex, const HTuple& ImageType, const HTuple& Width, const HTuple& Height);

// Selection of gray values by thresholding.
HUserExport void ExMapviewoffilewriteimage(const HObject& Image, const HTuple& iHandle, const HTuple& startindex);

// 	ex_mapviewoffilewrite
HUserExport void ExMapviewoffilewrite(const HTuple& iHandle, const HTuple& datatype, const HTuple& val, const HTuple& startindex);

// 	ex_mapviewoffilewriteint
HUserExport void ExMapviewoffilewriteint(const HTuple& iHandle, const HTuple& val, const HTuple& startindex);

// 	ex_mapviewoffileread
HUserExport void ExMapviewoffileread(const HTuple& iHandle, const HTuple& datatype, const HTuple& startindex, const HTuple& endindex, HTuple* val);

// 	ex_createfilemapping
HUserExport void ExCreatefilemapping(const HTuple& iFileMappingAttributes, const HTuple& iflProtect, const HTuple& idwMaximumSizeHigh, const HTuple& idwMaximumSizeLow, const HTuple& lpName, HTuple* iHandle);

// 	ex_openfilemapping
HUserExport void ExOpenfilemapping(const HTuple& dwDesiredAccess, const HTuple& bInheritHandle, const HTuple& lpName, const HTuple& chrsize, HTuple* iHandle);

// 	ex_initfilemapping
HUserExport void ExInitfilemapping(const HTuple& maxfilenum);

// 	ex_shellexecute
HUserExport void ExShellexecute(const HTuple& lpOperation, const HTuple& lpFile, const HTuple& nShowCmd);

// 	ex_winexec
HUserExport void ExWinexec(const HTuple& lpCmdLine, const HTuple& nShowCmd);

// 	ex_config_ini_delect_key
HUserExport void ExConfigIniDelectKey(const HTuple& filename, const HTuple& section, const HTuple& key);

// 	ex_config_ini_delect_section.
HUserExport void ExConfigIniDelectSection(const HTuple& filename, const HTuple& section);

// ex_config_ini_read_key_names.
HUserExport void ExConfigIniReadKeyNames(const HTuple& filename, const HTuple& section, HTuple* tups);

// config_ini_read_section_names.
HUserExport void ExConfigIniReadSectionNames(const HTuple& filename, HTuple* tups);

// ex_config_ini_write_str.
HUserExport void ExConfigIniWriteStr(const HTuple& filename, const HTuple& section, const HTuple& key, const HTuple& val);

// ex_config_ini_read_int.
HUserExport void ExConfigIniReadInt(const HTuple& filename, const HTuple& section, const HTuple& key, const HTuple& Defaultval, HTuple* val);

// ex_config_ini_read_str.
HUserExport void ExConfigIniReadStr(const HTuple& filename, const HTuple& section, const HTuple& key, const HTuple& Defaultval, HTuple* val);

// ex_config_ini_create .
HUserExport void ExConfigIniCreate(const HTuple& filename);

}

#endif
